export { default as MovieList } from './movieList'
export { default as SearchList } from './searchList'
export { default as Loader } from './loader'
export { default as ListAction} from './listAction'
export { default as MovieDetail } from './detail'